# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88e2b39e25fe8a1a21510d6cf43a9f5ff4a5acf7068d2afb92e70135e5facfcb31661ee62a8341fa2aca8617b32af1ae830ce934c438793c163c9b923af5e070

test:
  secret_key_base: 21120b66422215dce70e37e80f83bd4addaeaffdaf1573164705be59f38ccb483c9c15430a16507bd0afa39fb95b008b594962fbc916f5a89de430bb73307fa3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
